services:
  database_default:
    environment:
      POSTGRES_DB: db
      POSTGRES_HOST_AUTH_METHOD: trust
      SERVICE_MANAGER: fsm-postgres
    image: postgres:13.5-alpine
    volumes:
    - .:/app:rw
    - ./data:/data:rw
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    env_file: .env-local
    links:
    - database_default
    ports:
    - 8000:8000
    volumes:
    - .:/app:rw
    - ./data:/data:rw
version: '2'
