# Generated by Django 3.1.14 on 2022-02-07 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakBakGangIndex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bakbakgangindexpage',
            name='section_1',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='bakbakgangindexpage',
            name='section_2',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='bakbakgangindexpage',
            name='section_3',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='bakbakgangindexpage',
            name='section_4',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='bakbakgangindexpage',
            name='section_5',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='bakbakgangindexpage',
            name='section_5_banner',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
