# Generated by Django 3.1.14 on 2022-02-26 15:28

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('wagtailimages', '0023_add_choose_permissions'),
        ('bakBakGangIndex', '0002_auto_20220207_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bakbakgangindexpage',
            name='section_4_card',
            field=wagtail.core.fields.StreamField([('cards', wagtail.core.blocks.StructBlock([('order_by', wagtail.core.blocks.CharBlock(required=False)), ('description', wagtail.core.blocks.RichTextBlock(required=False))]))], blank=True, null=True),
        ),
        migrations.CreateModel(
            name='BolBehanPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('whatsapp_text', models.CharField(help_text='intro of the section', max_length=200)),
                ('section_1', models.CharField(blank=True, max_length=250, null=True)),
                ('section_1_title_1', wagtail.core.fields.RichTextField(blank=True)),
                ('section_1_sub_title_1', models.CharField(blank=True, max_length=250, null=True)),
                ('section_2', models.CharField(blank=True, max_length=250, null=True)),
                ('section_2_card', wagtail.core.fields.StreamField([('testimonial', wagtail.core.blocks.StructBlock([('description', wagtail.core.blocks.RichTextBlock(required=False))]))], blank=True, null=True)),
                ('section_3_card', wagtail.core.fields.StreamField([('cards', wagtail.core.blocks.StructBlock([('icon', wagtail.images.blocks.ImageChooserBlock(required=False)), ('description', wagtail.core.blocks.RichTextBlock(required=False))]))], blank=True, null=True)),
                ('section_4', models.CharField(blank=True, max_length=250, null=True)),
                ('section_4_description', wagtail.core.fields.RichTextField(blank=True)),
                ('section_4_card', wagtail.core.fields.StreamField([('cards', wagtail.core.blocks.StructBlock([('order_by', wagtail.core.blocks.CharBlock(required=False)), ('description', wagtail.core.blocks.RichTextBlock(required=False))]))], blank=True, null=True)),
                ('section_5', models.CharField(blank=True, max_length=250, null=True)),
                ('section_5_description', wagtail.core.fields.RichTextField(blank=True)),
                ('section_footer', wagtail.core.fields.StreamField([('cards', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(required=False)), ('description', wagtail.core.blocks.RichTextBlock(required=False))]))], blank=True, null=True)),
                ('header_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('section_1_main_img_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('section_1_main_img_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('section_2_main_img_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('section_5_main_img_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('whatsapp_icon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
