# Generated by Django 3.1.14 on 2022-02-26 17:33

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('bakBakGangIndex', '0003_auto_20220226_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='bolbehanpage',
            name='section_4_main_img_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='bakbakgangindexpage',
            name='section_4_card',
            field=wagtail.core.fields.StreamField([('cards', wagtail.core.blocks.StructBlock([('icon', wagtail.images.blocks.ImageChooserBlock(required=False)), ('description', wagtail.core.blocks.RichTextBlock(required=False))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bolbehanpage',
            name='section_3_card',
            field=wagtail.core.fields.StreamField([('section_3_cards', wagtail.core.blocks.StructBlock([('icon', wagtail.images.blocks.ImageChooserBlock(required=False)), ('description', wagtail.core.blocks.RichTextBlock(required=False))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bolbehanpage',
            name='section_4_card',
            field=wagtail.core.fields.StreamField([('section_4_cards', wagtail.core.blocks.StructBlock([('order_by', wagtail.core.blocks.CharBlock(required=False)), ('description', wagtail.core.blocks.RichTextBlock(required=False))]))], blank=True, null=True),
        ),
    ]
