# Generated by Django 3.2.12 on 2022-06-11 08:07

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bakBakGangIndex', '0004_auto_20220226_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='bakbakgangindexpage',
            name='faqcard',
            field=wagtail.core.fields.StreamField([('faqcard', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Enter title', required=True)), ('description', wagtail.core.blocks.TextBlock(help_text='Enter description', required=True)), ('featured', wagtail.core.blocks.BooleanBlock(required=True))]))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bolbehanpage',
            name='faqcard',
            field=wagtail.core.fields.StreamField([('faqcard', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Enter title', required=True)), ('description', wagtail.core.blocks.TextBlock(help_text='Enter description', required=True)), ('featured', wagtail.core.blocks.BooleanBlock(required=True))]))], blank=True, null=True),
        ),
    ]
