# Generated by Django 3.2.19 on 2023-06-29 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('bakBakGangIndex', '0007_auto_20220623_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='bolbehanpage',
            name='background_header_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
