# Generated by Django 3.2.19 on 2023-06-29 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakBakGangIndex', '0008_bolbehanpage_background_header_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bolbehanpage',
            name='header_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
