# Generated by Django 3.2.19 on 2023-06-29 13:46

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bakBakGangIndex', '0009_bolbehanpage_header_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='bolbehanpage',
            name='header_subtitle',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
