# Generated by Django 3.2.19 on 2023-06-29 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('bakBakGangIndex', '0010_bolbehanpage_header_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='bolbehanpage',
            name='messenger_icon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='bolbehanpage',
            name='messenger_text',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='bolbehanpage',
            name='messenger_url',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='bolbehanpage',
            name='whatsapp_url',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
