# Generated by Django 3.1.6 on 2021-08-30 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201109_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogindexpage',
            name='button',
            field=models.URLField(blank=True, verbose_name='read more'),
        ),
    ]
