# Generated by Django 3.1.13 on 2021-08-30 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_blogindexpage_button'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogindexpage',
            name='button',
            field=models.URLField(blank=True, verbose_name='read more'),
        ),
    ]
