# Generated by Django 3.1.13 on 2021-08-30 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0052_pagelogentry'),
        ('blog', '0009_remove_blogindexpage_button'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogindexpage',
            name='button',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
    ]
