# Generated by Django 3.1.1 on 2020-11-23 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_auto_20201117_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicepage',
            name='concern',
        ),
        migrations.AddField(
            model_name='servicepage',
            name='concern',
            field=models.ManyToManyField(blank=True, null=True, to='service.ConcernPage'),
        ),
    ]
