# Generated by Django 3.1.1 on 2020-11-24 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_auto_20201123_0616'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videosection',
            options={'verbose_name_plural': 'Arre Dekho'},
        ),
    ]
