# Generated by Django 3.1.1 on 2020-11-24 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_auto_20201124_1202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videosection',
            options={'verbose_name_plural': 'Arrey Dekho'},
        ),
    ]
