# Generated by Django 3.1.1 on 2020-11-25 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('service', '0008_remove_servicepage_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='videosection',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='videosection',
            name='image_link',
            field=models.URLField(blank=True, help_text='Url of the social page.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='videosection',
            name='video_link',
            field=models.URLField(blank=True, help_text='Url of the video', max_length=500, null=True),
        ),
    ]
