# Generated by Django 3.1.1 on 2020-11-25 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('service', '0009_auto_20201125_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videosection',
            name='image',
            field=models.ForeignKey(blank=True, help_text="if you are adding image then Please add image link also and don't add video link", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
