# Generated by Django 3.1.1 on 2020-11-26 06:52

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_auto_20201125_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepage',
            name='concern',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, null=True, to='service.ConcernPage'),
        ),
    ]
