# Generated by Django 3.1.1 on 2020-11-27 10:33

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_auto_20201126_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepage',
            name='concern',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='service.ConcernPage'),
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='location',
        ),
        migrations.AddField(
            model_name='servicepage',
            name='location',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='service.ServiceLocation'),
        ),
    ]
