# Generated by Django 3.1.1 on 2020-11-30 07:54

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_auto_20201127_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='concernindexpage',
            name='custom_text',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
