# Generated by Django 3.2.12 on 2022-07-04 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0016_auto_20220610_1559'),
        ('service', '0016_auto_20220610_1641'),
    ]

    operations = [
    ]
