# Generated by Django 3.2.19 on 2023-07-26 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0018_servicepage_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepagegalleryimage',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
