INSERT INTO rappidpro.rpp_ftbl_msgs_msg
SELECT  id,
        cast(uuid as varchar(65535)),
        cast(text as varchar(65535)),
        cast(high_priority as bigint),
        created_on,
        modified_on,
        cast(sent_on as timestamp),
        queued_on,
        cast(direction as varchar(1)),
        cast(status as varchar(1)),
        cast(visibility as varchar(1)),
        cast(msg_type as varchar(1)),
        msg_count,
        error_count,
        next_attempt,
        cast(external_id as varchar(255)),
        cast(attachments as varchar(2048)),
        cast(metadata as varchar(65535)),
        cast(delete_reason as varchar(1)),
        cast(broadcast_id as bigint),
        cast(channel_id as int4),
        cast(connection_id as int4),
        cast(contact_id as int4),
        cast(contact_urn_id as int4),
        cast(org_id as int8),
        cast(response_to_id as int4),
        cast(topup_id as int4),
        cast(contact_uuid  as VARCHAR(65535))
FROM rappidpro.staging_rpp_rpp_ftbl_msgs_msg;

