# Generated by Django 3.1.1 on 2020-10-26 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='section_about_descripton',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='section_about_icon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='section_about_title',
            field=models.CharField(default='', help_text='title of the about section', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='section_article_banner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='section_article_icon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='section_article_title',
            field=models.CharField(default='', help_text='title of the article section', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='section_concern_icon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='section_concern_title',
            field=models.CharField(default='', help_text='title of the concern section', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='section_social_title',
            field=models.CharField(default='', help_text='title of the social section', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='section_video_icon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='section_video_title',
            field=models.CharField(default='', help_text='title of the video section', max_length=200),
            preserve_default=False,
        ),
    ]
