# Generated by Django 3.1.1 on 2020-11-27 11:36

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_guidelinepage_privacypage_termpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guidelinepage',
            name='description',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='privacypage',
            name='description',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='termpage',
            name='description',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
