# Generated by Django 3.1.1 on 2020-12-03 11:38

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('home', '0008_auto_20201203_1122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='privacypage',
            old_name='description',
            new_name='head_description',
        ),
        migrations.RemoveField(
            model_name='termpage',
            name='footer_description',
        ),
        migrations.RemoveField(
            model_name='termpage',
            name='footer_icon',
        ),
        migrations.RemoveField(
            model_name='termpage',
            name='footer_title',
        ),
        migrations.RemoveField(
            model_name='termpage',
            name='head_description',
        ),
        migrations.RemoveField(
            model_name='termpage',
            name='head_image',
        ),
        migrations.RemoveField(
            model_name='termpage',
            name='simplecrousal',
        ),
        migrations.RemoveField(
            model_name='termpage',
            name='sub_title',
        ),
        migrations.AddField(
            model_name='privacypage',
            name='footer_description',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='privacypage',
            name='footer_icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='privacypage',
            name='footer_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='privacypage',
            name='head_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='privacypage',
            name='simplecrousal',
            field=wagtail.core.fields.StreamField([('simplecrousal', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Crousal title', max_length=100, required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('bg_color', wagtail.core.blocks.CharBlock(help_text='Background Color in HEX value', max_length=100, required=True)), ('text_color', wagtail.core.blocks.CharBlock(help_text='Text Color in HEX value', max_length=100, required=True)), ('description', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('description', wagtail.core.blocks.RichTextBlock(required=False))])))])), ('AdvanceCrousal', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text=' Add crousal title', max_length=100, required=True)), ('cards', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('title', wagtail.core.blocks.CharBlock(required=False)), ('description', wagtail.core.blocks.RichTextBlock(required=False))])))]))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='privacypage',
            name='sub_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='termpage',
            name='description',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
