# Generated by Django 3.1.1 on 2020-12-07 12:20

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0052_pagelogentry'),
        ('wagtailimages', '0022_uploadedimage'),
        ('home', '0010_auto_20201207_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityGuidline',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('sub_title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', wagtail.core.fields.RichTextField(blank=True)),
                ('icon_caption', models.CharField(blank=True, max_length=100, null=True)),
                ('footer_description', wagtail.core.fields.RichTextField(blank=True, help_text='Add description', null=True)),
                ('cards', wagtail.core.fields.StreamField([('communitypagecard', wagtail.core.blocks.StructBlock([('serial_number', wagtail.core.blocks.CharBlock(help_text='Add Serial Number', required=True)), ('serial_bg_color', wagtail.core.blocks.CharBlock(help_text='Add Serial Background Color in HEX value', required=True)), ('serial_text_color', wagtail.core.blocks.CharBlock(help_text='Add Serial Text Color in HEX value', required=True)), ('description', wagtail.core.blocks.RichTextBlock(help_text='Add description', required=False)), ('bg_color', wagtail.core.blocks.CharBlock(blank=True, default='#FFFFFF', help_text='Add Background Color in HEX value', null=True, required=True))]))], blank=True, null=True)),
                ('cover_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
