# Generated by Django 3.1.1 on 2020-12-10 10:56

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_communityguidline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privacypage',
            name='simplecrousal',
            field=wagtail.core.fields.StreamField([('simplecrousal', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Crousal title', max_length=100, required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('bg_color', wagtail.core.blocks.CharBlock(help_text='Background Color in HEX value', max_length=100, required=True)), ('text_color', wagtail.core.blocks.CharBlock(help_text='Text Color in HEX value', max_length=100, required=True)), ('description', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('description', wagtail.core.blocks.RichTextBlock(required=False))])))])), ('AdvanceCrousal', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text=' Add crousal title', max_length=100, required=True)), ('cards', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('title', wagtail.core.blocks.CharBlock(required=False)), ('description', wagtail.core.blocks.RichTextBlock(required=False))])))]))], blank=True, null=True),
        ),
    ]
