# Generated by Django 3.1.13 on 2021-11-11 05:14

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20201210_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', wagtail.core.fields.RichTextField(blank=True)),
                ('featured', models.BooleanField(default=False)),
            ],
        ),
    ]
