# Generated by Django 3.2.12 on 2022-06-11 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_homepage_faqcard'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FAQ',
        ),
    ]
