# Generated by Django 3.2 on 2022-10-21 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('home', '0020_alter_homepage_faqcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='section_event_icon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='section_event_title',
            field=models.CharField(default='testevent', help_text='title of the concern section', max_length=200),
            preserve_default=False,
        ),
    ]
