# Generated by Django 3.2 on 2022-10-21 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20221021_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='section_event_icon',
        ),
    ]
