# Generated by Django 3.2.12 on 2022-10-16 06:23

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('wagtailimages', '0023_add_choose_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='SahiSalahPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('event_title', models.CharField(blank=True, max_length=250, null=True)),
                ('event_body', wagtail.core.fields.RichTextField(blank=True)),
                ('instruction_title', models.CharField(blank=True, max_length=250, null=True)),
                ('instruction_body', wagtail.core.fields.RichTextField(blank=True)),
                ('timing_title', models.CharField(blank=True, max_length=250, null=True)),
                ('timing_body', models.CharField(blank=True, max_length=250, null=True)),
                ('price_title', models.CharField(blank=True, max_length=250, null=True)),
                ('price_body', models.CharField(blank=True, max_length=250, null=True)),
                ('location_title', models.CharField(blank=True, max_length=250, null=True)),
                ('location_body', models.CharField(blank=True, max_length=250, null=True)),
                ('whatsapp_text', models.CharField(help_text='intro of the section', max_length=200)),
                ('whatsapp_link', models.CharField(help_text='intro of the section', max_length=200)),
                ('header_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
