# Generated by Django 3.2.12 on 2022-10-16 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahi_salah', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sahisalahpage',
            name='timing_body',
        ),
        migrations.AddField(
            model_name='sahisalahpage',
            name='timing_date',
            field=models.DateField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='sahisalahpage',
            name='timing_time',
            field=models.TimeField(blank=True, max_length=250, null=True),
        ),
    ]
