# Generated by Django 3.2.12 on 2022-10-19 18:53

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('wagtailimages', '0023_add_choose_permissions'),
        ('sahi_salah', '0002_auto_20221016_0657'),
    ]

    operations = [
        migrations.CreateModel(
            name='SahiSalahIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.core.fields.RichTextField(blank=True)),
                ('section_1', models.CharField(blank=True, max_length=250, null=True)),
                ('card_1', models.CharField(help_text='intro of the section', max_length=200)),
                ('card_2', models.CharField(help_text='intro of the section', max_length=200)),
                ('card_3', models.CharField(help_text='intro of the section', max_length=200)),
                ('faqcard', wagtail.core.fields.StreamField([('faqcard', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Enter title', required=True)), ('description', wagtail.core.blocks.RichTextBlock(help_text='Enter description', required=False))]))], blank=True, null=True)),
                ('testimonial', wagtail.core.fields.StreamField([('testimonial', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.ListBlock(wagtail.core.blocks.CharBlock(help_text='Enter title', required=True)))]))], blank=True, null=True)),
                ('card_1_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('card_2_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('card_3_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('header_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
