# Generated by Django 3.2 on 2022-10-21 17:02

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sahi_salah', '0007_alter_sahisalahindexpage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sahisalahindexpage',
            name='content',
            field=wagtail.core.fields.StreamField([('faqcard', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Enter title', required=True)), ('description', wagtail.core.blocks.RichTextBlock(help_text='Enter description', required=False))]))], blank=True, null=True),
        ),
    ]
