# Generated by Django 3.2 on 2022-10-21 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sahi_salah', '0008_alter_sahisalahindexpage_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sahisalahindexpage',
            old_name='content',
            new_name='faqs',
        ),
    ]
