# Generated by Django 3.2 on 2022-10-21 17:09

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sahi_salah', '0009_rename_content_sahisalahindexpage_faqs'),
    ]

    operations = [
        migrations.AddField(
            model_name='sahisalahindexpage',
            name='testimonials',
            field=wagtail.core.fields.StreamField([('testimonials', wagtail.core.blocks.StructBlock([('testimonial', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Enter title', required=True))])))]))], blank=True, null=True),
        ),
    ]
