# Generated by Django 3.2.12 on 2022-11-15 16:54

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        # ('wagtailmenus', '0024_auto_20220610_1559'),
        ('wagtailcore', '0066_collection_management_permissions'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailimages', '0023_add_choose_permissions'),
        ('sahi_salah', '0011_alter_sahisalahindexpage_testimonials'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpcomingEventsArticle',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('event_title', models.CharField(blank=True, max_length=250, null=True)),
                ('event_body', wagtail.core.fields.RichTextField(blank=True)),
                ('instruction_title', models.CharField(blank=True, max_length=250, null=True)),
                ('instruction_body', wagtail.core.fields.RichTextField(blank=True)),
                ('timing_title', models.CharField(blank=True, max_length=250, null=True)),
                ('timing_date', models.DateField(blank=True, max_length=250, null=True)),
                ('timing_time', models.TimeField(blank=True, max_length=250, null=True)),
                ('price_title', models.CharField(blank=True, max_length=250, null=True)),
                ('price_body', models.CharField(blank=True, max_length=250, null=True)),
                ('location_title', models.CharField(blank=True, max_length=250, null=True)),
                ('location_body', models.CharField(blank=True, max_length=250, null=True)),
                ('cta_link', models.CharField(help_text='intro of the section', max_length=200)),
                ('cta_button', models.CharField(help_text='intro of the section', max_length=200)),
                ('content', wagtail.core.fields.StreamField([('crousalheader', wagtail.core.blocks.StructBlock([('images', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=False))])))]))], blank=True, null=True)),
                ('header_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AddField(
            model_name='sahisalahindexpage',
            name='whatsapp_link',
            field=models.CharField(blank=True, help_text='intro of the section', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sahisalahindexpage',
            name='yt_channel',
            field=models.CharField(blank=True, help_text='intro of the section', max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='SahiSalahPage',
        ),
    ]
