# Generated by Django 3.2.12 on 2022-11-09 06:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailimages', '0023_add_choose_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailcore', '0066_collection_management_permissions'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailmenus', '0024_auto_20220929_1204'),
        ('sahi_salah', '0011_alter_sahisalahindexpage_testimonials'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SahiSalahPage',
            new_name='UpcomingEventsArticle',
        ),
    ]
