# Generated by Django 3.2.12 on 2022-11-09 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahi_salah', '0012_rename_sahisalahpage_upcomingeventsarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='sahisalahindexpage',
            name='whatsapp_link',
            field=models.CharField(default=1, help_text='intro of the section', max_length=200),
            preserve_default=False,
        ),
    ]
