# Generated by Django 3.2.12 on 2022-11-14 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sahi_salah', '0012_auto_20221114_1349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upcomingeventsarticle',
            old_name='whatsapp_text',
            new_name='cta_link',
        ),
    ]
