# Generated by Django 3.2.12 on 2022-11-15 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahi_salah', '0013_rename_whatsapp_text_upcomingeventsarticle_cta_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='sahisalahindexpage',
            name='yt_channel',
            field=models.CharField(default=1, help_text='intro of the section', max_length=200),
            preserve_default=False,
        ),
    ]
